server:
  port: 8080

spring:
  application:
    name: price
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address:  http://127.0.0.1:30100
        serviceName: price
        version: 0.0.1
        healthCheckInterval: 30


