server:
  port: 8089

spring:
  application:
    name: product
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30300
        serviceName: product
        version: 0.0.1