server:
  port: 8081

spring:
  application:
    name: price
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        #serviceName: price
        version: 0.0.2
        healthCheckInterval: 30
        autoDiscovery: true