#
## ---------------------------------------------------------------------------
##
## Copyright (C) 2020-2026 Huawei Technologies Co., Ltd. All rights reserved.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
---
openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
paths:
  /stringRequestBody:
    post:
      tags:
        - schema-content-controller
      operationId: /stringRequestBody
      requestBody:
        content:
          application/json:
            schema: {}
        required: true
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
  /sayHelloPost:
    post:
      tags:
        - schema-content-controller
      operationId: /sayHelloPost
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
  /danglingPattern/**:
    post:
      tags:
        - schema-content-controller
      operationId: /danglingPattern/**
      requestBody:
        content:
          application/json:
            schema: {}
        required: true
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
  /sayHelloGet:
    get:
      tags:
        - schema-content-controller
      operationId: /sayHelloGet
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
    put:
      tags:
        - schema-content-controller
      operationId: /sayHelloGet_1
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
    post:
      tags:
        - schema-content-controller
      operationId: /sayHelloGet_2
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
    delete:
      tags:
        - schema-content-controller
      operationId: /sayHelloGet_3
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
    options:
      tags:
        - schema-content-controller
      operationId: /sayHelloGet_4
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
    head:
      tags:
        - schema-content-controller
      operationId: /sayHelloGet_5
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
    patch:
      tags:
        - schema-content-controller
      operationId: /sayHelloGet_6
      parameters:
        - name: id
          in: query
          required: true
          schema: {}
      responses:
        "200":
          description: OK
          content:
            application/vnd.hal+json:
              schema: {}
components:
  schemas: {}
