server:
  port: 8088

spring:
  application:
    name: order
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        serviceName: order
        version: 0.0.1

      credentials:
        enabled: true
        accessKey: your ak
        secretKey: your sk
        akskCustomCipher: default
        project: cn-east-2

      # testing servicecomb swagger generation
      swagger:
        enableJavaChassisAdapter: true

servicecomb:
  matchGroup:
    demo-rateLimiting: |
      matches:
        - apiPath:
            exact: "/govern/hello"
    demo-retry: |
      matches:
        - apiPath:
            prefix: "/retry"
    demo-circuitBreaker: |
      matches:
        - apiPath:
            exact: "/govern/circuitBreaker"
    demo-bulkhead: |
      matches:
        - apiPath:
            exact: "/govern/bulkhead"
  rateLimiting:
    demo-rateLimiting: |
      rate: 10
  retry:
    demo-retry: |
      maxAttempts: 3
  circuitBreaker:
    demo-circuitBreaker: |
      minimumNumberOfCalls: 10
      slidingWindowSize: 10
      failureRateThreshold: 20
  bulkhead:
    demo-bulkhead: |
      maxConcurrentCalls: 5
