server:
  port: 8088

spring:
  application:
    name: order
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        serviceName: order
        version: 0.0.1

      credentials:
        enabled: true
        accessKey: your ak
        secretKey: your sk
        akskCustomCipher: default
        project: cn-east-2

      # testing servicecomb swagger generation
      swagger:
        enableJavaChassisAdapter: true

servicecomb:
  matchGroup:
    demo-rateLimiting: |
      matches:
        - apiPath:
            exact: "/govern/hello"
          name: xx
    demo-retry: |
      matches:
        - apiPath:
            exact: "/govern/retry"
          name: xx
    demo-circuitBreaker: |
      matches:
        - apiPath:
            exact: "/govern/circuitBreaker"
          name: xx
    demo-bulkhead: |
      matches:
        - apiPath:
            exact: "/govern/bulkhead"
          name: xx
  rateLimiting:
    xxxxx: |
      rules:
        match: demo-rateLimiting.xx
      rate: 10
  retry:
    xxx: |
      rules:
        match: demo-retry.xx
      maxAttempts: 3
  circuitBreaker:
    xxx: |
      rules:
        match: demo-circuitBreaker.xx
      minimumNumberOfCalls: 10
      slidingWindowSize: 10
      failureRateThreshold: 20
  bulkhead:
    xxx: |
      rules:
        match: demo-bulkhead.xx
      maxConcurrentCalls: 5