---
swagger: "2.0"
info:
  description: "Api Documentation"
  version: "1.0"
  title: "swagger definition for com.huaweicloud.sample.SchemaContentController"
  termsOfService: "urn:tos"
  contact:
    name: ""
    url: ""
    email: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
  x-java-interface: "cse.gen.default.order.SchemaContentControllerIntf"
host: ""
basePath: "/"
tags: []
schemes: []
consumes: []
produces: []
paths:
  /sayHelloGet:
    get:
      tags:
        - "schema-content-controller"
      summary: "sayHelloGet"
      operationId: "sayHelloGet"
      schemes: []
      consumes: []
      produces:
        - "text/plain"
      parameters:
        - name: "id"
          in: "query"
          description: "id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
          examples: {}
          headers: {}
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
          examples: {}
          headers: {}
        "403":
          description: "Forbidden"
          examples: {}
          headers: {}
        "404":
          description: "Not Found"
          examples: {}
          headers: {}
      security: []
      deprecated: false
  /sayHelloPost:
    post:
      tags:
        - "schema-content-controller"
      summary: "sayHelloPost"
      operationId: "sayHelloPost"
      schemes: []
      consumes:
        - "application/json"
      produces:
        - "text/plain"
      parameters:
        - name: "id"
          in: "query"
          description: "id"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
          examples: {}
          headers: {}
          schema:
            type: "string"
        "201":
          description: "Created"
          examples: {}
          headers: {}
        "401":
          description: "Unauthorized"
          examples: {}
          headers: {}
        "403":
          description: "Forbidden"
          examples: {}
          headers: {}
        "404":
          description: "Not Found"
          examples: {}
          headers: {}
      security: []
      deprecated: false
  /stringRequestBody:
    post:
      tags:
        - "schema-content-controller"
      summary: "stringRequestBody"
      operationId: "stringRequestBody"
      schemes: []
      consumes:
        - "application/json"
      produces:
        - "text/plain"
      parameters:
        - in: "body"
          name: "id"
          description: "id"
          required: true
          schema:
            type: "string"
          x-raw-json: "true"
      responses:
        "200":
          description: "OK"
          examples: {}
          headers: {}
          schema:
            type: "string"
        "201":
          description: "Created"
          examples: {}
          headers: {}
        "401":
          description: "Unauthorized"
          examples: {}
          headers: {}
        "403":
          description: "Forbidden"
          examples: {}
          headers: {}
        "404":
          description: "Not Found"
          examples: {}
          headers: {}
      security: []
      deprecated: false
securityDefinitions: {}
definitions: {}
