server:
  port: 8094

spring:
  application:
    name: consumer
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        version: 0.0.2
        healthCheckInterval: 30
        autoDiscovery: true
feign:
  hystrix:
    enabled: true

servicecomb:
  routeRule:
    canary-provider: |
      - precedence: 1 #优先级
        route: #路由规则
          - weight: 80
            tags:
              version: 0.0.1
          - weight: 20
            tags:
              version: 0.0.2