server:
  port: 8093

spring:
  application:
    name: canary-provider
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-north-4.myhuaweicloud.com
        version: 0.0.2
        healthCheckInterval: 30
      credentials:
        enable: true
        accessKey: ak
        secretKey: sk
        project: cn-north-4
        akskCustomCipher: default