server:
  port: 8093

spring:
  application:
    name: canary-provider
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        version: 0.0.2
        healthCheckInterval: 30
        autoDiscovery: true