server:
  port: 8092

spring:
  application:
    name: canary-provider
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        version: 0.0.1
        healthCheckInterval: 30
      credentials:
        enabled: true
#        accessKey: ak
#        secretKey: sk
#        project: cn-north-4
#        akskCustomCipher: default