server:
  port: 8092

spring:
  application:
    name: canary-provider
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: ${engineAdd:https://cse.cn-north-4.myhuaweicloud.com}
        version: 0.1.1
        healthCheckInterval: 30
      credentials:
        enable: ${sslEnabled:true}
        accessKey: ${ak:yourak}
        secretKey: ${sk:yoursk}
        project: ${region:cn-north-4}
        akskCustomCipher: default