server:
  port: 8083

spring:
  application:
    name: zuul-service
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        version: 0.0.1
        healthCheckInterval: 30

zuul:
  routes:
    backend-service:
      path: /**
      serviceId: backend-service