server:
  port: 8091

spring:
  application:
    name: canary-consumer
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-north-4.myhuaweicloud.com
        version: 0.0.2
        healthCheckInterval: 30
        autoDiscovery: true

servicecomb:
  routeRule:
    canary-provider: |
      - precedence: 1 #优先级
        route: #路由规则
          - weight: 80
            tags:
              version: 0.0.1
          - weight: 20
            tags:
              version: 0.0.2